# Generated by Django 4.0.4 on 2022-05-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('edition', models.PositiveSmallIntegerField(default=1)),
                ('publication_year', models.PositiveSmallIntegerField()),
                ('authors', models.ManyToManyField(related_name='books', to='bookstore.author')),
            ],
            options={
                'ordering': ['-publication_year'],
            },
        ),
    ]
